# Generated by Django 4.2.6 on 2023-10-31 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha Atividade', max_length=255, verbose_name='Nome da Atividade')),
                ('quantidade_alunos', models.IntegerField(default=1, verbose_name='Quantidade de alunos')),
                ('dias_semana', models.CharField(default='Segunda, Quarta, Sexta', help_text='Escreva os dias da semana em que a atividade é realizada.', max_length=255, verbose_name='Dias da Semana')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_professor', to='professores.professores', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
