# Generated by Django 4.2.6 on 2023-10-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(default='Primeiro Nome', max_length=255, verbose_name='Primeiro Nome')),
                ('ultimo_nome', models.CharField(default='Ultimo Nome', max_length=255, verbose_name='Ultimo Nome')),
                ('cpf', models.CharField(default='00000000000', help_text='Por favor, digite apenas os números do CPF.', max_length=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
            ],
            options={
                'verbose_name': 'Professor(a)',
                'verbose_name_plural': 'Professores(as)',
            },
        ),
    ]
