# Generated by Django 4.2.6 on 2023-11-01 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Meu Nome', max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(default='Meu Sobrenome', max_length=255, verbose_name='Sobrenome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(default='00000000000', help_text='Por favor, digite apenas os números do CPF.', max_length=11, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, help_text='Ex: (16) 99999-9999', max_length=18, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-Mail')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='Masculino', max_length=255, verbose_name='Gênero')),
                ('deficiencia', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=255, verbose_name='PCD?')),
                ('ja_praticou', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=255, verbose_name='Já praticou o esporte?')),
                ('esporte', models.ForeignKey(default='Futebol', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividade_aluno', to='atividades.atividades', verbose_name='Esporte')),
            ],
            options={
                'verbose_name': 'Alunos(as)',
            },
        ),
    ]
